# Generated by Django 4.1.2 on 2022-11-03 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='room',
            new_name='Homes',
        ),
    ]
