# Generated by Django 4.1.2 on 2022-11-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_room_homes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homes',
            new_name='Home',
        ),
    ]
